# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Official CLI for managing Hostodo VPS instances"
  homepage "https://github.com/hostodo/cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/hostodo/cli/releases/download/v0.1.0/cli_0.1.0_Darwin_all.tar.gz"
    sha256 "eb27e7a168732bf8300f30650213c08904ab4127e4b63370e940bdca0fac1472"

    def install
      bin.install "hostodo"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v0.1.0/cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "082d53131683a740f532974dedbda2b5f968d6997be3f387f2e4729484e645bc"
      def install
        bin.install "hostodo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v0.1.0/cli_0.1.0_Linux_arm64.tar.gz"
      sha256 "5327ecbb7a9001c23b3a1cb2fc59660c97422c4b8093259fc7fa6bbc8875b594"
      def install
        bin.install "hostodo"
      end
    end
  end

  test do
    system "#{bin}/hostodo", "--version"
  end
end
