# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostodo < Formula
  desc "Official CLI for managing Hostodo VPS instances"
  homepage "https://github.com/hostodo/cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    url "https://github.com/hostodo/cli/releases/download/v0.1.4/cli_0.1.4_Darwin_all.tar.gz"
    sha256 "960a4541724b74c9e2dc1adf35bbbc5f52ad70b15a72fc679f3ee2aa7fd22531"

    def install
      bin.install "hostodo"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v0.1.4/cli_0.1.4_Linux_x86_64.tar.gz"
      sha256 "16ee6476321f6ce1962911cf099bef7c5ef33a3d824c8a0365a281b7d601932b"
      def install
        bin.install "hostodo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v0.1.4/cli_0.1.4_Linux_arm64.tar.gz"
      sha256 "e85d2c61ed09b3c30168ddbe0e86eae9e5e17a6c7d60647b3bec8f0ebc9bdf96"
      def install
        bin.install "hostodo"
      end
    end
  end

  test do
    system "#{bin}/hostodo", "--version"
  end
end
