# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostodo < Formula
  desc "Official CLI for managing Hostodo VPS instances"
  homepage "https://github.com/hostodo/cli"
  version "1.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/hostodo/cli/releases/download/v1.1.1/cli_1.1.1_Darwin_all.tar.gz"
    sha256 "1aa2bfe6a6a84629bff1c326aa69f4398f6839c596102ae18eff82cd5247a0ac"

    define_method(:install) do
      bin.install "hostodo"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v1.1.1/cli_1.1.1_Linux_x86_64.tar.gz"
      sha256 "8071e0905e9da32d44821f860331c6dc2703b28c4496a2863222e7f29eec4491"
      define_method(:install) do
        bin.install "hostodo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v1.1.1/cli_1.1.1_Linux_arm64.tar.gz"
      sha256 "fa76971b4c82f09e3b349072bd4e92776e9f097f72057711ee6900546c841e3a"
      define_method(:install) do
        bin.install "hostodo"
      end
    end
  end

  test do
    system "#{bin}/hostodo", "--version"
  end
end
