# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostodo < Formula
  desc "Official CLI for managing Hostodo VPS instances"
  homepage "https://github.com/hostodo/cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/hostodo/cli/releases/download/v1.0.0/cli_1.0.0_Darwin_all.tar.gz"
    sha256 "592beb2376bac061ae5a5ae89717ba9a91cac2df4adf1b230586c18f36b48dee"

    define_method(:install) do
      bin.install "hostodo"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v1.0.0/cli_1.0.0_Linux_x86_64.tar.gz"
      sha256 "2f3dfe5dab187f4e60fd55d357f8336099f5dbc8cfb29103b926d19c54425b29"
      define_method(:install) do
        bin.install "hostodo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v1.0.0/cli_1.0.0_Linux_arm64.tar.gz"
      sha256 "ba4219fee9e7a783ed3912ea4fedb4ea47946041d9575e77891f4707cab05144"
      define_method(:install) do
        bin.install "hostodo"
      end
    end
  end

  test do
    system "#{bin}/hostodo", "--version"
  end
end
