# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odo < Formula
  desc "Official CLI for managing Hostodo VPS instances"
  homepage "https://github.com/hostodo/cli"
  version "2.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/hostodo/cli/releases/download/v2.0.0/cli_2.0.0_Darwin_all.tar.gz"
    sha256 "21af9039475771fbe9a7831525c87e8d3dd8a56b6c31bc2fdc8a852c8365f6c5"

    define_method(:install) do
      bin.install "odo"
      generate_completions_from_executable(bin/"odo", "completion")
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v2.0.0/cli_2.0.0_Linux_x86_64.tar.gz"
      sha256 "bef511b3f87ce0d5ec51f7a2457782c993cb5efe1a79549aabdf3962b55a7d04"
      define_method(:install) do
        bin.install "odo"
        generate_completions_from_executable(bin/"odo", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/cli/releases/download/v2.0.0/cli_2.0.0_Linux_arm64.tar.gz"
      sha256 "d060cbe063c6195fc6951ac4522414f1b8bf6157965643a4369794c055d0afc8"
      define_method(:install) do
        bin.install "odo"
        generate_completions_from_executable(bin/"odo", "completion")
      end
    end
  end

  test do
    system "#{bin}/odo", "--version"
  end
end
