# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odo < Formula
  desc "Official CLI for managing Hostodo VPS instances"
  homepage "https://github.com/hostodo/odo-cli"
  version "2.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/hostodo/odo-cli/releases/download/v2.2.0/odo-cli_2.2.0_Darwin_all.tar.gz"
    sha256 "49107e64f157388b3b6b02abef02d7c7eb7ae0634aef2b05cd1c69b11b82a3a6"

    define_method(:install) do
      bin.install "odo"
      generate_completions_from_executable(bin/"odo", "completion")
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/odo-cli/releases/download/v2.2.0/odo-cli_2.2.0_Linux_x86_64.tar.gz"
      sha256 "c2a2309ab9df01a69be2c53547e57d0131b45b0a7071f6b0877ad2f104330a9a"
      define_method(:install) do
        bin.install "odo"
        generate_completions_from_executable(bin/"odo", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/odo-cli/releases/download/v2.2.0/odo-cli_2.2.0_Linux_arm64.tar.gz"
      sha256 "b4268adbadac9f7819617bc1064e1221a43e5fac715a766d6547ac2e5ab5caf1"
      define_method(:install) do
        bin.install "odo"
        generate_completions_from_executable(bin/"odo", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Shell completions have been installed. To enable them, add the following
      to your ~/.zshrc (if not already present):

        autoload -Uz compinit && compinit

      Then restart your shell or run: source ~/.zshrc

      For bash, add to ~/.bashrc:
        [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && \
          source "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/odo", "--version"
  end
end
