# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odo < Formula
  desc "Official CLI for managing Hostodo VPS instances"
  homepage "https://github.com/hostodo/odo-cli"
  version "2.0.4"
  license "MIT"

  on_macos do
    url "https://github.com/hostodo/odo-cli/releases/download/v2.0.4/odo-cli_2.0.4_Darwin_all.tar.gz"
    sha256 "157677df6bf200c6119e15f483a3609458cb68c1a646e7398b887bdc2765ac7b"

    define_method(:install) do
      bin.install "odo"
      generate_completions_from_executable(bin/"odo", "completion")
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/odo-cli/releases/download/v2.0.4/odo-cli_2.0.4_Linux_x86_64.tar.gz"
      sha256 "3bbfbc3bff7381711d8f9845fc877f8758c99878078cf66d4d5305665204274b"
      define_method(:install) do
        bin.install "odo"
        generate_completions_from_executable(bin/"odo", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostodo/odo-cli/releases/download/v2.0.4/odo-cli_2.0.4_Linux_arm64.tar.gz"
      sha256 "9d57281b46f4b9f23fffe5764e74cfbd5663a8da1b641b802b9acb3f536cf16a"
      define_method(:install) do
        bin.install "odo"
        generate_completions_from_executable(bin/"odo", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Shell completions have been installed. To enable them, add the following
      to your ~/.zshrc (if not already present):

        autoload -Uz compinit && compinit

      Then restart your shell or run: source ~/.zshrc

      For bash, add to ~/.bashrc:
        [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && \
          source "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/odo", "--version"
  end
end
